# Generated by Django 5.2.7 on 2025-10-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hangout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="discord_user_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_from_discord",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["discord_user_id"], name="hangout_mes_discord_9522df_idx"
            ),
        ),
    ]
